before_script:
  - "ruby --version"
  - "bundle exec rake test_app"
script: "bundle exec rake"
notifications:
  irc:
    channels:
      - "irc.freenode.org#spree"
    use_notice: true
    skip_join: true

  
branches:
  only:
    - master
    - namespace
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
